[package]
name = "mintlayer-app"
version = "0.1.0"
edition = "2021"

[dependencies]
messages = { path = "./messages" }
ledger_device_sdk = "1.27.3"
ledger_secure_sdk_sys = "1.11.5"
include_gif = "1.2.4"
serde = { version = "1.0.228", default-features = false, features = ["derive"] }
serde-json-core = { git = "https://github.com/rust-embedded-community/serde-json-core" }
hex = { version = "0.4.3", default-features = false, features = [
    "serde",
    "alloc",
] }
numtoa = "0.3.1"

bech32 = { version = "0.11", default-features = false, features = ["alloc"] }
chrono = { version = "0.4", default-features = false, features = ["alloc"] }

ml_common = { git = "https://github.com/mintlayer/mintlayer-core", package = "trezor-common", branch = "feature/hardware-wallet-common2" }

[build-dependencies]
image = "0.25.8"

[profile.release]
opt-level = 'z'
lto = true

[features]
default = ["ledger_device_sdk/nano_nbgl"]
debug = ["ledger_device_sdk/debug"]

[package.metadata.ledger]
curve = ["secp256k1"]
flags = "0"
path = ["44'/19788'", "44'/1'"]
name = "Mintlayer"

[package.metadata.ledger.nanox]
icon = "icons/mintlayer_14x14.gif"

[package.metadata.ledger.nanosplus]
icon = "icons/mintlayer_14x14.gif"

[package.metadata.ledger.stax]
icon = "icons/mintlayer_32x32.gif"

[package.metadata.ledger.flex]
icon = "icons/mintlayer_40x40.gif"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(target_os, values("apex_p", "stax", "flex", "nanos", "nanox", "nanosplus"))',
] }
