[package]
name = "mintlayer-app"
version.workspace = true
edition = "2021"

[workspace]
members = ["crates/app-core", "crates/messages"]
resolver = "2"

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
bech32 = { version = "0.11", default-features = false }
chrono = { version = "0.4", default-features = false }
derive_more = { version = "2.1", default-features = false }
hex = { version = "0.4", default-features = false }
image = "0.25"
ledger_device_sdk = "1.35"
ledger_secure_sdk_sys = "1.16"
num_enum = { version = "0.7", default-features = false }
num-traits = { version = "0.2", default-features = false }
# Note: the testmacro crate is published by Ledger and its source code comes from the `testmacro`
# dir inside the sdk repo, i.e. https://github.com/LedgerHQ/ledger-device-rust-sdk/tree/cad196841dbd72c037cfa01bec81a4a3ae57a04e/testmacro
# (though the published version is a bit older).
testmacro = "0.1"

mintlayer-app-core = { path = "crates/app-core" }
mintlayer-messages = { path = "crates/messages" }

[workspace.dependencies.parity-scale-codec]
git = "https://github.com/paritytech/parity-scale-codec.git"
# Use the specific commit "5021525697edc0661591ebc71392c48d950a10b0",
# which includes a fix for NanoX devices that do not support certain
# atomic operations.
#
# Fix reference: https://github.com/paritytech/parity-scale-codec/pull/751
# This fix should be included in releases after version 3.7.5.
rev = "5021525697edc0661591ebc71392c48d950a10b0"
default-features = false

[workspace.dependencies.mintlayer-core-primitives]
git = "https://github.com/mintlayer/mintlayer-core-primitives"
# The commit "Merge pull request #4 from mintlayer/fix_typo".
rev = "8644bfe06d932d687075939d2d175183ba1c369d"
package = "mintlayer-core-primitives"

[dependencies]
ledger_device_sdk.workspace = true

mintlayer-app-core.workspace = true

[build-dependencies]
image.workspace = true

[[bin]]
# Note: we only have this section to disable tests, but Cargo inists that "name" should also
# be specified.
name = "mintlayer-app"
# The app bin crate is a thin wrapper around `mintlayer-app-core` and it's not supposed to have
# unit tests of its own. So we disable tests completely to prevent Cargo from producing an uncompilable
# test binary.
test = false

[package.metadata.ledger]
curve = ["secp256k1"]
flags = "0"
path = ["44'/19788'", "44'/1'"]
name = "Mintlayer"

[package.metadata.ledger.nanox]
icon = "media/icons/mintlayer_14x14.gif"

[package.metadata.ledger.nanosplus]
icon = "media/icons/mintlayer_14x14.gif"

[package.metadata.ledger.stax]
icon = "media/icons/mintlayer_32x32.gif"

[package.metadata.ledger.flex]
icon = "media/icons/mintlayer_40x40.gif"

[package.metadata.ledger.apex_p]
icon = "media/icons/mintlayer_32x32.png"
