[package]
name = "mintlayer-app"
version = "0.1.0"
edition = "2021"

[dependencies]
messages = { path = "./messages" }
ledger_device_sdk = "1.34.0"
ledger_secure_sdk_sys = "1.16.1"
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
bech32 = { version = "0.11", default-features = false, features = ["alloc"] }
chrono = { version = "0.4", default-features = false, features = ["alloc"] }

[dependencies.mintlayer-core-primitives]
git = "https://github.com/mintlayer/mintlayer-core-primitives"
# The commit "Merge pull request #4 from mintlayer/fix_typo".
rev = "8644bfe06d932d687075939d2d175183ba1c369d"
package = "mintlayer-core-primitives"

[build-dependencies]
image = "0.25.8"

[features]
default = ["ledger_device_sdk/nano_nbgl"]
debug = ["ledger_device_sdk/debug"]

[package.metadata.ledger]
curve = ["secp256k1"]
flags = "0"
path = ["44'/19788'", "44'/1'"]
name = "Mintlayer"

[package.metadata.ledger.nanox]
icon = "icons/mintlayer_14x14.gif"

[package.metadata.ledger.nanosplus]
icon = "icons/mintlayer_14x14.gif"

[package.metadata.ledger.stax]
icon = "icons/mintlayer_32x32.gif"

[package.metadata.ledger.flex]
icon = "icons/mintlayer_40x40.gif"

[package.metadata.ledger.apex_p]
icon = "icons/mintlayer_32x32.png"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(target_os, values("apex_p", "stax", "flex", "nanos", "nanox", "nanosplus"))',
] }
