[package]
name = "mintlayer-app-core"
version.workspace = true
edition = "2021"

[dependencies]
bech32 = { workspace = true, default-features = false, features = ["alloc"] }
chrono = { workspace = true, default-features = false, features = ["alloc"] }
hex = { workspace = true, default-features = false, features = ["alloc"] }
ledger_device_sdk.workspace = true
ledger_secure_sdk_sys.workspace = true

mintlayer-core-primitives.workspace = true
mintlayer-messages.workspace = true

[features]
default = ["ledger_device_sdk/nano_nbgl"]
debug = ["ledger_device_sdk/debug"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(target_os, values("apex_p", "stax", "flex", "nanos", "nanox", "nanosplus"))',
] }
