[package]
name = "messages"
version = "0.1.0"
edition = "2024"

[dependencies]
# Use the specific commit "5021525697edc0661591ebc71392c48d950a10b0",
# which includes a fix for NanoX devices that do not support certain
# atomic operations.
#
# Fix reference: https://github.com/paritytech/parity-scale-codec/pull/751
# This fix should be included in releases after version 3.7.5.
# Note: normally we would enable the "chain-error" feature of parity-scale-codec to make decode errors
# more informative. But in the Ledger app we never examine or even print those errors, so enabling this
# feature would only increase the size of the binary and make the app use more stack during decoding.
parity-scale-codec = { git = "https://github.com/paritytech/parity-scale-codec.git", rev = "5021525697edc0661591ebc71392c48d950a10b0", default-features = false, features = [
  "derive",
] }

num_enum = { version = "0.7.5", default-features = false }
derive_more = { version = "2.1.1", default-features = false, features = [
  "display",
] }

[dependencies.mintlayer-core-primitives]
git = "https://github.com/mintlayer/mintlayer-core-primitives"
# The commit "Merge pull request #4 from mintlayer/fix_typo".
rev = "8644bfe06d932d687075939d2d175183ba1c369d"
package = "mintlayer-core-primitives"
