[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]

# By default, heap size is enforced to 8192 bytes.
# Authorized values are [2048, 4096, 8192, 16384, 24576]
# We use 16k as we get some crashes on 8k when running the tests with big 20+ input TXs
[env]
HEAP_SIZE = "16384"
