/*****************************************************************************
 *   Mintlayer Ledger App.
 *   (c) 2025-2026 RBB S.r.l.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *****************************************************************************/

use alloc::string::String;

use ledger_device_sdk::{ecc::ECPublicKey, include_gif, nbgl::NbglGlyph};

use mintlayer_core_primitives::PUBLIC_KEY_HASH_SIZE;
use mintlayer_messages::{Destination, PublicKeyHash, Secp256k1PublicKey, encode, encode_to};

use crate::{StatusWord, hasher::Hasher, mlcp, utils::cut_array};

pub fn bech32m_encode(hrp: &str, data: &[u8]) -> Result<String, StatusWord> {
    let parsed_hrp = bech32::Hrp::parse(hrp).map_err(|_| StatusWord::AddressEncodingFail)?;

    let encoded = bech32::encode::<bech32::Bech32m>(parsed_hrp, data)
        .map_err(|_| StatusWord::AddressEncodingFail)?;

    Ok(encoded)
}

pub fn to_address(destination: &Destination, coin: mlcp::CoinType) -> Result<String, StatusWord> {
    let hrp = coin.address_prefix(destination.into());
    bech32m_encode(hrp, &encode(destination))
}

// TODO: all image files currently contain the Rust logo; need to replace them with Mintlayer logo.
// See https://github.com/mintlayer/mintlayer-ledger-app/issues/10.
/// Load glyph from file with include_gif macro. Creates an NBGL compatible glyph.
pub const fn load_glyph() -> NbglGlyph<'static> {
    #[cfg(target_os = "apex_p")]
    const GLYPH: NbglGlyph =
        NbglGlyph::from_include(include_gif!("../../media/glyphs/mintlayer_48x48.png", NBGL));
    #[cfg(any(target_os = "stax", target_os = "flex"))]
    const GLYPH: NbglGlyph =
        NbglGlyph::from_include(include_gif!("../../media/glyphs/mintlayer_64x64.gif", NBGL));
    #[cfg(any(target_os = "nanosplus", target_os = "nanox"))]
    // Note: the original boilerplate app used different images on nano devices, depending on whether
    // it's for review screens or for the menu. Moreover, in the menu case the file, called
    // "home_nano_nbgl.png", was generated by `build.rs` based on "mask_14x14.gif"; the gist was
    // that the inscribed circle area of the image was inverted, while the remaining corner areas
    // were turned black. The purpose of this is unclear, as all screens have black background
    // on nano devices, so the generated image didn't look better on the menu screen. In any case,
    // even if we decide to use different images based on purpose, it's better to pre-make a nice
    // alternative image instead of generating it.
    const GLYPH: NbglGlyph =
        NbglGlyph::from_include(include_gif!("../../media/icons/mintlayer_14x14.gif", NBGL));

    GLYPH
}

pub fn compress_public_key<const T: char>(
    public_key: &ECPublicKey<65, T>,
) -> Result<Secp256k1PublicKey, StatusWord> {
    let uncompressed_key = &public_key.pubkey;
    if uncompressed_key[0] != 0x04 {
        return Err(StatusWord::InvalidUncompressedPublicKey);
    }

    let mut compressed_key = [0u8; 33];

    let y_coordinate = &uncompressed_key[33..65];
    let prefix = if y_coordinate[31].is_multiple_of(2) {
        0x02
    } else {
        0x03
    };

    compressed_key[0] = prefix;

    let x_coordinate = &uncompressed_key[1..33];
    compressed_key[1..].copy_from_slice(x_coordinate);

    Ok(Secp256k1PublicKey(compressed_key))
}

pub fn to_public_key_hash(pk: &Secp256k1PublicKey) -> Result<PublicKeyHash, StatusWord> {
    let mut hasher = Hasher::new();

    encode_to(&mlcp::PublicKey::Secp256k1Schnorr(*pk), &mut hasher);

    let full_hash = hasher.finalize()?;
    let pkh: [u8; PUBLIC_KEY_HASH_SIZE] = cut_array(full_hash.as_fixed_bytes());

    Ok(PublicKeyHash(pkh))
}
